name: Deploy

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version to deploy'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check Docker image existence
        run: |
          if ! docker pull cr.yandex/<registry_id>/app:${{ github.event.inputs.release_version }}_latest; then
            echo "Docker image not found!"
            exit 1
          fi
      - name: Deploy to VM
        run: |
          ssh -o StrictHostKeyChecking=no -i /path/to/your/private/key user@your_vm_ip 'docker pull cr.yandex/<registry_id>/app:${{ github.event.inputs.release_version }}_latest && docker run -d -p 3000:3000 cr.yandex/<registry_id>/app:${{ github.event.inputs.release_version }}_latest'
      - name: Create GitHub Issue Comment
        run: gh issue comment <issue_number> --body "Deployed release ${{ github.event.inputs.release_version }}"
